#!/usr/bin/env node
// generate.mjs: emit derived surfaces from catalog.json. Dependency-free.
//   docs/CATALOG.md   human table: id | purpose | access | inputs
//   mcp-tools.json    every graph query as an MCP tool descriptor, all KEYED
//   sdk-methods.json  method stubs (one per entry) for SDK codegen
//
// The whisper.security graph is a KEYED surface: it is Cypher, so every tool here
// needs an API key. The two-tier split lives at the WHISPER level: the genuine
// keyless half is the non-Cypher identity ops (verify/rdap), which are NOT in this
// catalog. `playgroundTryable` is carried through so a surface can show a
// "try without a key" hint on the single-request direct-read verbs (rate-limited
// playground, 100/window).

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const catalog = JSON.parse(readFileSync(join(root, 'catalog.json'), 'utf8'));
const entries = catalog.entries;

const camel = s => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const inputList = e => e.inputs.length
  ? e.inputs.map(i => `\`${i.paramName}\`${i.default !== undefined ? ` (e.g. ${JSON.stringify(i.default)})` : ''}`).join(', ')
  : '_none_';

// ---- docs/CATALOG.md ----
const accessCell = e => `${e.access}${e.playgroundTryable ? ' · playground' : ''}`;
const rows = entries.map(e =>
  `| \`${e.id}\` | ${e.purpose.replace(/\|/g, '\\|')} | ${accessCell(e)} | ${inputList(e).replace(/\|/g, '\\|')} |`
).join('\n');

const tryableN = entries.filter(e => e.playgroundTryable).length;

const md = `<!-- generated by scripts/generate.mjs (do not edit by hand) -->
# Whisper Query Catalog

The portable, provenance-backed catalog of \`whisper.security\` graph queries and read flows.

- **Endpoint:** \`${catalog.graph.endpoint}\`
- **Request:** \`${catalog.graph.request}\`
- **Response envelope:** \`${catalog.graph.envelope}\`, where ${catalog.graph.rowsShape}.
- **Auth:** ${catalog.graph.auth}
- **Keyed:** ${catalog.graph.keyed}
- **Playground:** ${catalog.graph.playground}

${entries.length} entries, **all keyed** (it is Cypher; Cypher needs a key). ${tryableN} are \`playground · tryable\` (single-request direct reads you can *taste* keyless within the 100/window playground).

| id | purpose | access | inputs |
|----|---------|--------|--------|
${rows}

_Generated at ${catalog.generatedAt}. Every entry is provenance-backed (live-probed shape)._
`;
writeFileSync(join(root, 'docs', 'CATALOG.md'), md);

// ---- mcp-tools.json (every graph query, all KEYED; playground hint carried through) ----
const mcpTools = entries.map(e => {
  const properties = {};
  const required = [];
  for (const i of e.inputs) {
    const t = ['number'].includes(i.kind) ? 'number' : 'string';
    properties[i.paramName] = {
      type: t,
      description: `${i.id}${i.examples ? ` (e.g. ${i.examples.slice(0, 3).join(', ')})` : ''}`,
      ...(i.default !== undefined ? { default: i.default } : {}),
      ...(i.options ? { enum: i.options } : {}),
    };
    if (i.default === undefined) required.push(i.paramName);
  }
  return {
    name: `whisper_${camel(e.id)}`,
    description: `${e.purpose} ${e.why ?? ''}`.trim(),
    inputSchema: { type: 'object', properties, required },
    _exec: e.exec,
    _access: e.access,               // always "keyed" (it is Cypher)
    _requiresKey: true,              // graph tools need an API key
    _playgroundTryable: e.playgroundTryable, // sample keyless in the 100/window playground?
    _resultColumns: e.columns,
  };
});
writeFileSync(join(root, 'mcp-tools.json'), JSON.stringify({
  generatedAt: catalog.generatedAt,
  endpoint: catalog.graph.endpoint,
  auth: catalog.graph.auth,
  note: 'Every tool here runs Cypher against the whisper.security graph, so every tool is KEYED (supply X-API-Key). The keyless half of Whisper is the non-Cypher identity tools (verify/rdap), which are not in this catalog. Tools with _playgroundTryable:true can be sampled without a key in the rate-limited playground (100/window).',
  tools: mcpTools,
}, null, 2) + '\n');

// ---- sdk-methods.json (method stubs for every entry) ----
const sdkMethods = entries.map(e => ({
  method: camel(e.id),
  access: e.access,                  // always "keyed"
  requiresKey: true,                 // it is Cypher
  playgroundTryable: e.playgroundTryable,
  mode: e.exec.mode,
  params: e.inputs.map(i => ({ name: i.paramName, kind: i.kind, required: i.default === undefined, default: i.default ?? null })),
  cypher: e.exec.cypher ?? null,
  runVia: e.exec.runVia ?? null,
  returns: e.columns,
  summary: e.purpose,
}));
writeFileSync(join(root, 'sdk-methods.json'), JSON.stringify({
  generatedAt: catalog.generatedAt,
  endpoint: catalog.graph.endpoint,
  auth: catalog.graph.auth,
  methods: sdkMethods,
}, null, 2) + '\n');

console.log(`generate: wrote docs/CATALOG.md, mcp-tools.json (${mcpTools.length} keyed graph tools, ${tryableN} playground-tryable), sdk-methods.json (${sdkMethods.length} methods)`);
