#!/usr/bin/env node
// generate.mjs: emit derived surfaces from catalog.json. Dependency-free.
//   docs/CATALOG.md   human table: id | purpose | access | inputs
//   mcp-tools.json    every graph query as an MCP tool descriptor
//   sdk-methods.json  method stubs (one per entry) for SDK codegen
//
// The whisper.security graph is TWO-TIER. The single-request direct READ procedures
// (assess, identify, explain, variants, walk, origins, history, ...) serve KEYLESS:
// no key, rate-limited (~100/window), real answers -- this is `access:"keyless"`,
// which equals `playgroundTryable`. Raw Cypher, the multi-step FLOWS, and the write
// verb (submit) are KEYED (`access:"keyed"`, X-API-Key). Sending a key on any call
// lifts the rate limit. So `requiresKey === !playgroundTryable`.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const catalog = JSON.parse(readFileSync(join(root, 'catalog.json'), 'utf8'));
const entries = catalog.entries;

const camel = s => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const inputList = e => e.inputs.length
  ? e.inputs.map(i => `\`${i.paramName}\`${i.default !== undefined ? ` (e.g. ${JSON.stringify(i.default)})` : ''}`).join(', ')
  : '_none_';

// Docs deep-link: every entry carries a root-relative docPath; the absolute URL is
// docsBase + docPath, so any channel can render a "docs" link with zero extra config.
const docsUrl = e => catalog.graph.docsBase + e.docPath;

// Flow-run contract: flow entries are runnable via the gallery run endpoint (SSE).
// The per-entry copy carries the entry's own id as the concrete slug.
const flowRunFor = e => e.exec.mode === 'flow'
  ? { ...catalog.graph.flowRun, bodyShape: { ...catalog.graph.flowRun.bodyShape, slug: e.id } }
  : null;

// ---- docs/CATALOG.md ----
const accessCell = e => `${e.access}${e.playgroundTryable ? ' · playground' : ''}`;
const rows = entries.map(e =>
  `| \`${e.id}\` | ${e.purpose.replace(/\|/g, '\\|')} | ${accessCell(e)} | ${inputList(e).replace(/\|/g, '\\|')} | [${e.docPath}](${docsUrl(e)}) |`
).join('\n');

const tryableN = entries.filter(e => e.playgroundTryable).length;

const md = `<!-- generated by scripts/generate.mjs (do not edit by hand) -->
# Whisper Query Catalog

The portable, provenance-backed catalog of \`whisper.security\` graph queries and read flows.

- **Endpoint:** \`${catalog.graph.endpoint}\`
- **Request:** \`${catalog.graph.request}\`
- **Response envelope:** \`${catalog.graph.envelope}\`, where ${catalog.graph.rowsShape}.
- **Auth:** ${catalog.graph.auth}
- **Keyed:** ${catalog.graph.keyed}
- **Playground:** ${catalog.graph.playground}
- **Docs base:** \`${catalog.graph.docsBase}\` (each entry's docs link = docsBase + docPath)
- **Flow run:** \`${catalog.graph.flowRun.method} ${catalog.graph.flowRun.endpoint}\` (header \`${catalog.graph.flowRun.auth}\`, body \`{"slug":"<flow id>","inputs":{},"params":{}}\`, ${catalog.graph.flowRun.transport} stream). ${catalog.graph.flowRun.note}

${entries.length} entries, two-tier: **${tryableN} keyless** direct read procedures (no key, rate-limited ~100/window, real answers -- add a key to lift the limit) and **${entries.length - tryableN} keyed** (raw Cypher, the multi-step flows, and submit need \`X-API-Key\`).

| id | purpose | access | inputs | docs |
|----|---------|--------|--------|------|
${rows}

_Generated at ${catalog.generatedAt}. Every entry is provenance-backed (live-probed shape)._
`;
writeFileSync(join(root, 'docs', 'CATALOG.md'), md);

// ---- mcp-tools.json (every graph query; keyless read procs + keyed flows/raw/submit) ----
const mcpTools = entries.map(e => {
  const properties = {};
  const required = [];
  for (const i of e.inputs) {
    const t = ['number'].includes(i.kind) ? 'number' : 'string';
    properties[i.paramName] = {
      type: t,
      description: `${i.id}${i.examples ? ` (e.g. ${i.examples.slice(0, 3).join(', ')})` : ''}`,
      ...(i.default !== undefined ? { default: i.default } : {}),
      ...(i.options ? { enum: i.options } : {}),
    };
    if (i.default === undefined && !i.optional) required.push(i.paramName);
  }
  const flowRun = flowRunFor(e);
  return {
    name: `whisper_${camel(e.id)}`,
    description: `${e.purpose} ${e.why ?? ''}`.trim(),
    inputSchema: { type: 'object', properties, required },
    _exec: e.exec,
    _access: e.access,               // "keyless" (direct read proc) | "keyed" (flow/raw/submit)
    _requiresKey: !e.playgroundTryable, // keyless read procs work without a key (rate-limited); the rest need X-API-Key
    _playgroundTryable: e.playgroundTryable, // keyless-capable? (== access "keyless")
    _resultColumns: e.columns,
    _docPath: e.docPath,
    _docsUrl: docsUrl(e),
    ...(flowRun ? { _flowRun: flowRun } : {}),
  };
});
writeFileSync(join(root, 'mcp-tools.json'), JSON.stringify({
  generatedAt: catalog.generatedAt,
  endpoint: catalog.graph.endpoint,
  auth: catalog.graph.auth,
  docsBase: catalog.graph.docsBase,
  flowRun: catalog.graph.flowRun,
  note: 'The whisper.security graph is two-tier. Tools with _requiresKey:false (== _access "keyless", the direct read procedures: assess, identify, explain, variants, walk, origins, history, ...) run WITHOUT a key, rate-limited (~100/window) with real answers; send X-API-Key to lift the limit. Tools with _requiresKey:true (raw Cypher, the multi-step flows, and submit) need X-API-Key. Each tool carries _docPath/_docsUrl (docsBase + docPath) for its documentation page; flow tools carry _flowRun (POST the slug to the run endpoint, SSE stream).',
  tools: mcpTools,
}, null, 2) + '\n');

// ---- sdk-methods.json (method stubs for every entry) ----
const sdkMethods = entries.map(e => ({
  method: camel(e.id),
  access: e.access,                  // "keyless" (direct read proc) | "keyed" (flow/raw/submit)
  requiresKey: !e.playgroundTryable, // keyless read procs work without a key (rate-limited); the rest need X-API-Key
  playgroundTryable: e.playgroundTryable,
  mode: e.exec.mode,
  params: e.inputs.map(i => ({ name: i.paramName, kind: i.kind, required: i.default === undefined && !i.optional, default: i.default ?? null })),
  cypher: e.exec.cypher ?? null,
  runVia: e.exec.runVia ?? null,
  flowRun: flowRunFor(e),
  returns: e.columns,
  summary: e.purpose,
  docPath: e.docPath,
  docsUrl: docsUrl(e),
}));
writeFileSync(join(root, 'sdk-methods.json'), JSON.stringify({
  generatedAt: catalog.generatedAt,
  endpoint: catalog.graph.endpoint,
  auth: catalog.graph.auth,
  docsBase: catalog.graph.docsBase,
  flowRun: catalog.graph.flowRun,
  methods: sdkMethods,
}, null, 2) + '\n');

console.log(`generate: wrote docs/CATALOG.md, mcp-tools.json (${mcpTools.length} graph tools: ${tryableN} keyless read procs + ${mcpTools.length - tryableN} keyed), sdk-methods.json (${sdkMethods.length} methods)`);
